services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: ./backend-project/infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./backend-project/src
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-youcan}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
  web:
    image: web
    container_name: web
    build:
      context: .
      dockerfile: ./backend-project/infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./backend-project/src
        target: /workspace
  db:
    image: db
    container_name: db
    build:
      context: .
      dockerfile: ./backend-project/infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3306}
        protocol: tcp
        mode: host
    configs:
      - source: db-config
        target: /etc/my.cnf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-youcan}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
  vue-app:
    image: vue-app
    container_name: vue-app
    build:
      context: .
      dockerfile: ./frontend-project/Dockerfile
    ports:
      - "8080:8080"
    volumes:
    - type: bind
      source: ./frontend-project/src
      target: /usr/src/app/src
    - type: bind
      source: ./backend-project/src/storage/app/public/images
      target: /usr/src/app/public/images
    working_dir: /usr/src/app
  adminer-app:
    build:
      context: .
      dockerfile: ./backend-project/infra/docker/adminer/Dockerfile
    image: adminer
    container_name: adminer-app
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
volumes:
  db-store:
  psysh-store:
configs:
  db-config:
    file: ./backend-project/infra/docker/mysql/my.cnf